<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Activity Location' => '',
  'Activity Location Related Place' => '',
  'Arrival Date Time Actual' => '',
  'Arrival Date Time Estimated' => '',
  'Bookingreference Number' => '',
  'Car Reg Number' => '',
  'Carrier' => '',
  'Conveyance Reference Number' => '',
  'Create Datetime' => '',
  'Create Etpr Terminal Prices' => '',
  'Date Time Preparation' => '',
  'Departure Date Time Estimated' => '',
  'ETPR_CONTAINER_SIZE_20' => '20',
  'ETPR_CONTAINER_SIZE_40' => '40',
  'ETPR_CONTAINER_STATUS_EMPTY' => 'Empty',
  'ETPR_CONTAINER_STATUS_FULL' => 'Full',
  'ETPR_OPERATION_LOADING' => 'Load',
  'ETPR_OPERATION_LOADING_RW' => 'Load RW',
  'ETPR_OPERATION_LOADING_TRUCK' => 'Load Truck',
  'ETPR_OPERATION_MOVING_LT_STORAGE' => 'Move to LT',
  'ETPR_OPERATION_MOVING_SS_PLACE' => 'Move to SS',
  'ETPR_OPERATION_STORAGE' => 'Storeage',
  'Edifact' => '',
  'Edifact Data' => '',
  'Edifact Datas' => '',
  'Equipment Identification' => '',
  'Etpr' => '',
  'Etpr Container Size' => 'Size',
  'Etpr Container Status' => 'Status',
  'Etpr Date From' => 'From',
  'Etpr Date To' => 'To',
  'Etpr Day From' => 'Day From',
  'Etpr Day To' => 'Day To',
  'Etpr H68 2020 Coefficient' => 'Spec Hour Coef.',
  'Etpr Hour Holiday Coefficient' => 'Hol. Coef.',
  'Etpr Imdg Coefficient' => 'IMDG Coef.',
  'Etpr Imdg Price' => 'IMDG price',
  'Etpr Notes' => 'Notes',
  'Etpr Operation' => 'Operation',
  'Etpr Price' => '',
  'Etpr Terminal' => 'Terminal',
  'Etpr Terminal Prices' => 'Price',
  'Filename' => '',
  'Gross Weight' => '',
  'ID' => '',
  'Id Of The Means Of Transport Vessel' => '',
  'Interchange Sender' => '',
  'Message' => '',
  'Message Ref Number' => '',
  'Message Reference Number' => '',
  'Message Type' => '',
  'Port Of Discharge' => '',
  'Positioning Datetime Of Equipment' => '',
  'Prep Datetime' => '',
  'Realise Reference Number' => '',
  'Tare Weight' => '',
  'Terminal' => '',
  'tooltip.etpr_container_size' => '',
  'tooltip.etpr_container_status' => '',
  'tooltip.etpr_date_from' => '',
  'tooltip.etpr_date_to' => '',
  'tooltip.etpr_day_from' => '',
  'tooltip.etpr_day_to' => '',
  'tooltip.etpr_h68_2020_coefficient' => '',
  'tooltip.etpr_hour_holiday_coefficient' => '',
  'tooltip.etpr_id' => '',
  'tooltip.etpr_imdg_coefficient' => '',
  'tooltip.etpr_imdg_price' => '',
  'tooltip.etpr_notes' => '',
  'tooltip.etpr_operation' => '',
  'tooltip.etpr_price' => '',
  'tooltip.etpr_terminal' => '',
);
